http:
  bindAddress: :8013
  mode: debug #(debugreleasetest)
db:
  Host: localhost
  Port: 3306
  DBName: notification_service
  User: root
  Password: 123456
  ConnLifeTime: 300
  ConnTimeOut: 30
  MaxIdleConns: 10
  MaxOpenConns: 80
  LogLevel: 1
redis:
  RedisAddresses: :6379
  Password:
  MasterName:
common:
  LogLevel: -1 #debug
  HttpClientRetryCount: 2
  HttpClientRetryWaitTimeSeconds: 3
  HttpClientRetryMaxWaitTimeSeconds: 10
